/* XPM */
static char * four_xpm[] = {
"50 50 54 1",
" 	c #000000",
".	c #999999",
"+	c #ABABAB",
"@	c #535353",
"#	c #D3D3D3",
"$	c #F5F5F5",
"%	c #E7E7E7",
"&	c #787878",
"*	c #EAEAEA",
"=	c #FDFDFD",
"-	c #F4F4F4",
";	c #C5C5C5",
">	c #F6F6F6",
",	c #FFFFFF",
"'	c #ECECEC",
")	c #5D5D5D",
"!	c #DDDDDD",
"~	c #FEFEFE",
"{	c #FCFCFC",
"]	c #EFEFEF",
"^	c #B1B1B1",
"/	c #B6B6B6",
"(	c #F0F0F0",
"_	c #8A8A8A",
":	c #595959",
"<	c #E5E5E5",
"[	c #DBDBDB",
"}	c #F7F7F7",
"|	c #D5D5D5",
"1	c #FAFAFA",
"2	c #9B9B9B",
"3	c #CCCCCC",
"4	c #BDBDBD",
"5	c #D0D0D0",
"6	c #F8F8F8",
"7	c #F2F2F2",
"8	c #8D8D8D",
"9	c #E6E6E6",
"0	c #9E9E9E",
"a	c #F1F1F1",
"b	c #FBFBFB",
"c	c #E9E9E9",
"d	c #A8A8A8",
"e	c #BBBBBB",
"f	c #CFCFCF",
"g	c #C4C4C4",
"h	c #C9C9C9",
"i	c #D6D6D6",
"j	c #DFDFDF",
"k	c #EEEEEE",
"l	c #DADADA",
"m	c #F3F3F3",
"n	c #F9F9F9",
"o	c #E8E8E8",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                   .++@                           ",
"                   #$%&                           ",
"                   *=-&                           ",
"                  ;>,')                           ",
"                  !~{!                            ",
"                  ]{{^                            ",
"                 /-,(_                            ",
"                :<~~[                             ",
"                &>~}+                             ",
"                |1,%                              ",
"                <~{|                              ",
"               2-~}2                              ",
"               |{~<:                              ",
"              :*~{3          :44+                 ",
"              56~72          8-=9                 ",
"              !~{!:          0=,6                 ",
"             _a{b^           0~,{                 ",
"             51,c_           d~,b                 ",
"            +7~{5            e~,1                 ",
"           :|~,]_            f,,{:                ",
"           g1,~ahhhhhij*kaaaa6,,b2                ",
"           g~,~1666666==,,,,,,,,=l                ",
"           /k666666666--aaaaaam=~9                ",
"            :&dehhhhhed&:     h{{9                ",
"                              hnnf                ",
"                              h66h                ",
"                              e66i                ",
"                              d-=j                ",
"                              &-=*                ",
"                              :a,k                ",
"                               a,a                ",
"                               a,a                ",
"                               a,a                ",
"                               a,a                ",
"                               a,a                ",
"                               k,a:               ",
"                               [1o:               ",
"                               +44:               ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "};
