/* XPM */
static char * exitgameS_xpm[] = {
"280 80 309 2",
"  	c #000000",
". 	c #701464",
"+ 	c #AB2499",
"@ 	c #911D82",
"# 	c #9B701F",
"$ 	c #473209",
"% 	c #624610",
"& 	c #AF259D",
"* 	c #CF2DB9",
"= 	c #D12EBB",
"- 	c #B927A5",
"; 	c #B98727",
"> 	c #D29A2E",
", 	c #A17521",
"' 	c #AF8025",
") 	c #B38326",
"! 	c #B68526",
"~ 	c #C08C29",
"{ 	c #C6912B",
"] 	c #996F1F",
"^ 	c #7F5B18",
"/ 	c #705114",
"( 	c #B78627",
"_ 	c #BE8B29",
": 	c #C7912B",
"< 	c #956C1E",
"[ 	c #47093F",
"} 	c #C22AAD",
"| 	c #D22EBC",
"1 	c #C92CB4",
"2 	c #CC952D",
"3 	c #BD8A29",
"4 	c #C6902B",
"5 	c #CD962D",
"6 	c #D1992E",
"7 	c #CF972D",
"8 	c #CC962D",
"9 	c #CF982D",
"0 	c #CA942C",
"a 	c #C18D29",
"b 	c #A77A23",
"c 	c #43083B",
"d 	c #150112",
"e 	c #1F7014",
"f 	c #2A911D",
"g 	c #31A522",
"h 	c #AB7D24",
"i 	c #D0982D",
"j 	c #C5902B",
"k 	c #621057",
"l 	c #CA2CB4",
"m 	c #A12190",
"n 	c #094146",
"o 	c #13666D",
"p 	c #1A7E86",
"q 	c #1C858E",
"r 	c #1D8891",
"s 	c #1D8790",
"t 	c #18777F",
"u 	c #105B62",
"v 	c #D0982E",
"w 	c #D0992E",
"x 	c #C9932C",
"y 	c #8C1B7D",
"z 	c #A62294",
"A 	c #9C208B",
"B 	c #19073D",
"C 	c #250D55",
"D 	c #2E1164",
"E 	c #37B626",
"F 	c #3EC92C",
"G 	c #3FCC2D",
"H 	c #3DC62B",
"I 	c #3BC029",
"J 	c #3BC22A",
"K 	c #33AB24",
"L 	c #13510B",
"M 	c #C8922B",
"N 	c #CE972D",
"O 	c #8A1B7B",
"P 	c #C92CB3",
"Q 	c #D22EBB",
"R 	c #D02DBA",
"S 	c #239BA5",
"T 	c #26A7B2",
"U 	c #27AAB4",
"V 	c #27A9B4",
"W 	c #27A8B3",
"X 	c #25A3AE",
"Y 	c #1B7F87",
"Z 	c #CB952C",
"` 	c #BC8928",
" .	c #91691D",
"..	c #C28E2A",
"+.	c #AD249B",
"@.	c #CC2CB6",
"#.	c #C32AAF",
"$.	c #431D8E",
"%.	c #4C219E",
"&.	c #5024A8",
"*.	c #4F23A6",
"=.	c #5124A9",
"-.	c #5425AE",
";.	c #5526B0",
">.	c #5023A7",
",.	c #401B87",
"'.	c #3FCD2D",
").	c #40CF2D",
"!.	c #41D22E",
"~.	c #40CE2D",
"{.	c #A27621",
"].	c #C38E2A",
"^.	c #D2992E",
"/.	c #9B1F8A",
"(.	c #CE2DB8",
"_.	c #B927A6",
":.	c #A72395",
"<.	c #25A2AD",
"[.	c #28ACB7",
"}.	c #28ACB6",
"|.	c #A57822",
"1.	c #A07521",
"2.	c #B326A0",
"3.	c #07393D",
"4.	c #0D4F55",
"5.	c #115E64",
"6.	c #2C1062",
"7.	c #3B187F",
"8.	c #441D90",
"9.	c #471E95",
"0.	c #4C219F",
"a.	c #4F23A5",
"b.	c #5727B4",
"c.	c #5928B7",
"d.	c #5828B6",
"e.	c #40D02E",
"f.	c #41D12E",
"g.	c #3DC72B",
"h.	c #33AA23",
"i.	c #8C651B",
"j.	c #A82396",
"k.	c #C52AB0",
"l.	c #951E85",
"m.	c #B727A4",
"n.	c #CD2DB7",
"o.	c #7F1871",
"p.	c #249EA9",
"q.	c #27ACB7",
"r.	c #27A9B3",
"s.	c #20929C",
"t.	c #A22190",
"u.	c #14676E",
"v.	c #21959F",
"w.	c #239CA6",
"x.	c #24A0AA",
"y.	c #249EA8",
"z.	c #26A5B0",
"A.	c #239DA7",
"B.	c #5627B3",
"C.	c #5827B7",
"D.	c #5828B7",
"E.	c #481F97",
"F.	c #39177A",
"G.	c #3ABD29",
"H.	c #104709",
"I.	c #258219",
"J.	c #951D85",
"K.	c #CB2CB6",
"L.	c #C32AAE",
"M.	c #C129AC",
"N.	c #C72BB2",
"O.	c #B626A2",
"P.	c #28ABB6",
"Q.	c #C82BB2",
"R.	c #C82BB3",
"S.	c #27ABB6",
"T.	c #28ADB8",
"U.	c #27AAB5",
"V.	c #5526B1",
"W.	c #5827B5",
"X.	c #5627B2",
"Y.	c #CB942C",
"Z.	c #CB2CB5",
"`.	c #D02EBA",
" +	c #A72295",
".+	c #C029AC",
"++	c #25A4AF",
"@+	c #25A1AC",
"#+	c #249FA9",
"$+	c #249DA8",
"%+	c #1F8E97",
"&+	c #17737A",
"*+	c #4B219D",
"=+	c #5225AB",
"-+	c #5325AD",
";+	c #3CC52A",
">+	c #40D02D",
",+	c #B48326",
"'+	c #B526A2",
")+	c #CD2DB8",
"!+	c #CF2DBA",
"~+	c #CA2CB5",
"{+	c #1F8C95",
"]+	c #20929B",
"^+	c #1B8089",
"/+	c #4A209C",
"(+	c #301268",
"_+	c #735315",
":+	c #C48F2A",
"<+	c #BD28A9",
"[+	c #C52BB0",
"}+	c #991F89",
"|+	c #CC2DB7",
"1+	c #BC28A8",
"2+	c #C029AB",
"3+	c #26A6B1",
"4+	c #CC952C",
"5+	c #BE29AA",
"6+	c #C42AAF",
"7+	c #A52293",
"8+	c #2299A3",
"9+	c #25A4AE",
"0+	c #115C63",
"a+	c #BD8A28",
"b+	c #C92BB3",
"c+	c #AA2398",
"d+	c #146970",
"e+	c #39BC28",
"f+	c #35AF25",
"g+	c #1F8D96",
"h+	c #247F18",
"i+	c #CE2DB9",
"j+	c #2297A0",
"k+	c #21939D",
"l+	c #381778",
"m+	c #4D22A0",
"n+	c #A32191",
"o+	c #209099",
"p+	c #C62BB1",
"q+	c #3F1A86",
"r+	c #492099",
"s+	c #731567",
"t+	c #8A641B",
"u+	c #B426A1",
"v+	c #9C208C",
"w+	c #177178",
"x+	c #4E22A2",
"y+	c #5727B5",
"z+	c #38B927",
"A+	c #AA7C23",
"B+	c #AC2499",
"C+	c #BA28A6",
"D+	c #5224AA",
"E+	c #5928B8",
"F+	c #5827B6",
"G+	c #CC2CB7",
"H+	c #A77A22",
"I+	c #AD7E24",
"J+	c #B08125",
"K+	c #C4902A",
"L+	c #C82CB3",
"M+	c #BF8B29",
"N+	c #B28225",
"O+	c #931D83",
"P+	c #CE2DB7",
"Q+	c #CF982E",
"R+	c #C5902A",
"S+	c #BF29AA",
"T+	c #A0218F",
"U+	c #249FAA",
"V+	c #2298A2",
"W+	c #A07420",
"X+	c #AC7D24",
"Y+	c #24A0AB",
"Z+	c #197880",
"`+	c #1C838C",
" @	c #936B1D",
".@	c #1E8C95",
"+@	c #36B225",
"@@	c #2D9B1F",
"#@	c #3DC82B",
"$@	c #3CC42A",
"%@	c #3ABE29",
"&@	c #5727B3",
"*@	c #40D12E",
"=@	c #2D991F",
"-@	c #3FCB2C",
";@	c #811873",
">@	c #4D22A2",
",@	c #32A723",
"'@	c #196210",
")@	c #3ECA2C",
"!@	c #3CC32A",
"~@	c #288A1B",
"{@	c #3DC52B",
"]@	c #1E8992",
"^@	c #30A221",
"/@	c #288C1B",
"(@	c #36B326",
"_@	c #30A121",
":@	c #51390B",
"<@	c #2B951E",
"[@	c #BA8828",
"}@	c #1C858D",
"|@	c #AC249A",
"1@	c #3FCC2C",
"2@	c #BD29A9",
"3@	c #17727A",
"4@	c #24A1AB",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                . + + @                                                                                                                         ",
"            # # #                                                                                                                                                                                                                                                                                                                                             $ % % $                                                                           & * = -                                                                                                                         ",
"            ; > ;   $ , ' ) ! ~ { { ~ ! ] ^ $                                                                                                                                                                                                                                                                                                           / , ( _ : : ( < $                                                                     [ } | | 1 .                                                                                                                       ",
"            { > 2 3 4 5 6 7 8 > > > > 9 9 0 a ( b ^ $       c [ [ d                                                                                                                                                                                                                                 e f g g g g f e                                     h 8 i 6 6 6 6 j , $                                                                   k l | | * m                           n o p q r s s s s s s s s s s s s s s s s s s s s s s t u                                   ",
"            { > v w > 6 6 7 8 { { { x 6 6 6 i 6 9 x h       y z A [                                                                                                                                                           B C D C B                                                         e f E F G G G G G H I J E K L                         / M > > 0 j N w 6 x ,                             y y y                                 O P Q | R &                           u S T U V W W W W W W W W W W W W W W W W W W W W W W X Y                                   ",
"            { > v i i Z ` '  ./      .! ....: Z 6 6 h       +.@.#.O                                                                                                                                       B C D D $.%.&.*.*.*.=.-.;.>.,.                                                      e K '.).).'.G G G G !.!.~.!.I e                         {.9 > 0 < ^ , ].6 ^.M ,                           /.(._./.                              :.* = = (.-                           u <.[.}.V W W W W W W W W W W W W W W W W W W W W W W X Y                                   ",
"            { > Z |.{.^ $                 $ % 1._ ` {.      2.= * 2.                                                              3.4.5.5.5.5.5.5.5.5.4.3.          6.7.8.8.8.8.8.8.8.8.8.8.8.9.0.a.*.*.*.=.-.;.;.b.c.c.d.d.d.d.d.d.b.,.                                                    e E ~.e.f.g.h.g g g E I H ~.F I e                       $ ` 6 N '       i.a 6 > ..^                         j.l | k.l.                            m.= = n.| } o.                        n p.q.r.s.s s s s s s s s s s s s s s s s s s s s s s t u                                   ",
"            { > {                                           t.* = }                                                     u.v.w.x.y.X z.z.z.z.z.z.z.z.z.A.Y           ,.-.B.B.B.B.B.B.B.B.B.B.B.b.b.d.C.D.d.d.d.d.d.c.c.b.;.;.;.-.=.*.E.F.                                                  e E ).f.).G.K H.          e I.f e L                       ^ Z 6 : %         i.j ^.i (                         J.K.Q Q L.y                         [ M.= (.N.* R O.                          w.P.z.5.                                                                                  ",
"            { > {                                           . Q.| R.o.                                /././.          u S S.T.U.T.T.P.P.P.P.P.P.P.P.P.U Y           ,.-.B.B.B.B.B.B.B.B.B.B.B.b.B.V.b.W.X.-.=.*.*.&.%.$.D D D C B                                                         K ~.f.).E e                                               b 9 ^._             < 5 > Y.i.                      +.Z.= | = +                         k N.`.L.z * Q }                           w.P.z.5.                                                                                  ",
"            { > {                                             M.= R  +                              . .+| O.          u ++[.P.U.X @+#+A.$+$+w.w.w.w.w.%+&+          6.7.8.8.8.8.8.8.8.8.8.8.8.8.7.*+=+-+,.C B                                                                           e ;+f.>+E e                                                 ( 6 N )             $ ..> 6 ,+                      '+* )+!+= ~+:.[                     O P R m.o.K.= P o.                        w.P.z.5.                                                                                  ",
"            { > {                                             m.= R 2.                              & R = .+          u {+v.]+t u     &+r ^+3.                                                    /+W.=+(+                                                                              K ).!.;+e                                                 $ a v M _+              , Z 6 :+/                     <+= (.[+R | l m                     }+|+|+& [ 1+= R -                         w.P.z.5.                                                                                  ",
"            { > {                                             t.@.* 2+@                           . 1 | R +                           %+3+w.4.                                                  B =.d.-.C                                                                             e ;+f.).K                                                   % : i a $               $ ' 5 4+h                     m.= = 5+6+Q = 1+                    7+|+|+7+  t.* = }                         w.P.z.5.                                                                                  ",
"            { > {                                             . O.* R O.                        [ O.R | k..                           8+S.9+0+                                                  C -.d.=.B                                                                             K ).!.;+e                                                   _+x i a+                  / { > ..$                   & * R - y 6+| b++ @                 7+n.n.c+  . 1 (.k.                        w.}.3+d+                                                                                  ",
"            { > {                                               @ * = k.                        l.K.| Z.t.                            w.P.z.5.                                                  D ;.d.*.                                                                              e+f.).f+                                                    _+x i a+                    ~ > 5 h                   7+n.n.c+  /.& * `.[+y               & * R -     1+| } k                       w.[.U.g+                                                                                  ",
"            { > {                                               . Q.| ~+l.                    . L.= R m.                              w.P.z.5.                                                  D ;.d.*.                                                                            f H f.g.h+                                                    _+x i a+                    ! 9 ^.!                   7+|+|+7+    o.P | = 1+[             m.= = 2.    M.= i+ +                      j+[.[.k+                                                                                  ",
"            { > {                                                 1+= = &                   [ + * Q k.o.                              w.P.z.5.                                                  l+;.d.m+                                                                            E e.).E H.                                                    _+x i a+                     .5 7 ../                 @ |+|+O.    [ + @.| * O..           <+= n.n+    m.= = 2.                      o+U.U.k+                                                                                  ",
"            { > {                                                 t.* `.p+.                 o.K.Q (.+                                 w.P.z.5.                                                  q+B.B.r+                                                                            G.f.).g                                                       _+x i a+                    / ' 8 x {.                . p+| .+        & (.| * O..         <+R P s+    & * * 2.                      s W W s                                                                                   ",
"            { > {                                                 . } | (.+               [ - R | 5+[                                 w.P.z.5.                                                  8.B.B.8.                                                                            G.~.~.f                                                       _+x i a+                      ] x i '                   p+| p+        . 1+R = (.+       [ M.R N.k     @ |+|+O.                      s W W s                                                                                   ",
"            { > {                                                   + * = k..           [ m K.| K.+                                   w.P.z.5.                                                  8.B.B.8.                                                                          h+J !.I e                                                       _+x i a+                      t+8 8 (                   p+| p+          . O.* = p+}+[   k N.R M.[     . p+| .+                      s W W s                                                                                   ",
"            { > {                                                   . Q.| * m           o.[+= (.u+                                    w.P.z.5.                                                  8.B.B.8.                                                                          E >+).E                                                         _+x i a+                      ^ 0 6 M ^                 6+| p+[           . - R = l /.  s+P R <+        6+| p+[                     p W W o+                                                                                  ",
"            { > {                                                     u+= R 5+[       [ & * = } .                                     w.P.z.5.                                                  8.B.B.8.                                                                          G.!.).g                                                         t+5 6 ].                      $ ..^.9 ]                 M.`.l s+            o.P | Q p+/.O P R m.        M.= n.v+                    w+z.P.j+                                                                                  ",
"            { > {                                                     y Q.| @.m       m l = (.+                                       w.P.z.5.                                                  x+y+y+8.                                                                          z+).).g                                                         ] 9 ^...                        ; 9 9 A+                <+= i+B+            [ + Q.| | .+c+|+|+&         m.= = 2.                    5.z.P.w.                                                                                  ",
"            { > {                                                       m.= = C+[   . 5+| = 1+.                                       w.P.z.5.                                                  D+E+F+q+                                                                          g G G g                                                         |.9 i 3                         ] 8 8 '                 m.= = 2.                /.1 | R N.(.|+7+        & * R -                     5.z.P.w.                                                                                  ",
"            { > {                                                       l.K.= G+m   + * = K./.                                        w.P.z.5.                                                  -+c.b.l+                                                                          E G G f                                                         |.5 5 A+                        ^ : i ` $               & * * 2.                  + * = = = * 2.        @ n.n.-                     5.z.P.w.                                                                                  ",
"            { > {                                                       [ 1+= = & . k.| = & [                                         w.P.z.5.                                                  &.d.V.D                                                                           I !.H e                                                         |.8 8 |.                        $ a 6 0 t+              7+|+|+7+                  . 1+= Q | Q 2.        . p+| .+                    5.z.P.w.                                                                                  ",
"            :+> { $     % H+) ) |.' ( a+a+a+I+i.                          :.* * C+@ * = ~+y                                           w.P.z.5.                                                  *.d.;.D                                                                           H !.H                                                           |.8 8 |.                          ( 6 i )               }+|+|+&                     y 5+| | R  +          6+| p+[                   5.z.[.T w.w.w.w.j+o+s s s s t u                                                           ",
"            a i 0 J+_ j K+N 6 7 8 8 i i i i N #                           o.N.= L+6+* R O.                                            w.P.z.5.                                                  *.d.;.D                                                                           H !.H                                                           |.8 8 |.                          ' 9 6 ;               O P R m.                      l.n.= N.k           M.R P k                   5.z.[.[.P.P.P.[.[.S.W W W W X Y                                                           ",
"            a+i N 0 6 6 w 6 6 7 8 8 x x x x M+#                           [ m.= Q = R L.@                                             w.P.z.5.                                                  *.d.;.D                                                                           H !.H                                                           |.8 8 |. .! 3 N+! ~ { { { { { { ; ; N N ;               k N.R M.[                     [ m m l.            L.= )+O+                  5.z.[.U.z.z.z.V T.S.W W W W X Y                                                           ",
"            a+i N N 7 5 M a ( ' |.] t+_+_+_+% $                             l.P+| | = 7+                                              w.P.z.5.                                                  *.d.;.D                                                                           H !.H                                                           |.N Q+M R+6 6 N 8 > > > > > > > > ) x i (               [ M.= K.v+                                        S+Q R T+                  5.z.P.U+5.5.5.g+k+V+s s s s t u                                                           ",
"            a+i 5 J+W+t+% $                                                 [ [+| | `.@                                               w.P.z.5.                                                  *.d.;.D                                                                           H !.H                                                           |.N 6 5 > 9 9 N 8 { { { { { { { ; X+x i a+                m.= = 2.                                        - * * c+                  5.z.P.w.                                                                                  ",
"            a+i x _+                                                        [ L+| | * .                                               w.P.z.5.                                                  *.d.;.D                                                                           I !.H e                                                         |.N Q+M ! ! |.|. ./               % : i a $               & * R -                                         }+|+|+&                   5.z.P.w.                                                                                  ",
"            a+i x _+                                                        o.)+| | `.+                                               Y+[.V Z+                                                  *.d.;.D                                                                           E G G f                                                         |.8 8 |.                          $ a i : %               7+n.n.c+                                        O P R m.                  5.z.P.w.                                                                                  ",
"            a+i x _+                                                      [ & R = = `.1+                                              A.T.S.`+                                                  *.d.;.D                                                                           g ).).z+                                                        |.8 8 |.                            ].6 5  @              7+|+|+7+                                        s+P R <+                  5.z.P.w.                                                                                  ",
"            a+i x _+                                                      o.K.= n.(.= P l.                                            V+S.S..@                                                  *.d.;.D                                                                           g ).!.G.                                                        |.8 8 |.                            M+^.i 1.              @ |+|+O.                                        k N.R M.[                 5.z.P.w.                                                                                  ",
"            a+i x _+                                                      :.* | .+m.= = m.                                            s W W s                                                   *.d.;.D                                                                           g ).>+G.                  e f g +@G.G.g e                       |.8 8 |.                            ; 9 9 A+              . p+| .+                                        [ M.R N.k                 5.z.P.w.                                                                                  ",
"            a+i x _+                                                    . 1+= K.& l.n.= b+o.                                          s W W s                                                   *.d.;.D                                                                           f '.'.z+                  @@#@).>+f.f.~.$@J %@f+h+              |.8 8 |.                            |.8 8 |.                6+| p+[                                         <+= )+B+                5.z.P.w.                                                                                  ",
"            a+i x _+                                                    t.* * } [ [ C+= R m.                                          p W W o+                                                  *.D.&@$.                                                                          e I !.J h+                @@#@>+!.e.).~.!.*@f.>+;+K e           |.8 8 |.                            ] 8 8 '                 M.R P k                                         m.= | 2.                5.z.P.w.                                                                                  ",
"            a+i x _+                                                  . 5+= | &     l.)+Q N.[                                         w+z.P.j+                                                  m+c.c.*+                                                                            E ).>+E                 e =@G.G.z+g E I -@).f.f.G K           |.8 8 |.                            t+x i (                 <+`.l ;@                                        & * * -                 5.z.P.w.                                                                                  ",
"            a+i x _+                                                  t.* = ~+m     [ k.| (.+                                         5.z.P.w.                                                  r+F+F+>@                                                                            g ).!.G.                              H.h+,@J e.!.I           |.8 8 |.                            % : i a $               <+= i+B+                                        @ |+|+O.                4.9+P.#+3.                                                                                ",
"            a+i x _+                                                [ 1+= = &         + * | k..                                       5.z.P.w.                                                  8.b.b.9.                                                                            f ).).J                                     h+F !.$@          |.8 8 |.                            $ a i : %               m.= = 2.                                        . p+| .+                3.#+P.9+4.                                                                                ",
"            a+i x _+                                                o.l = P l.        . Q.| R +                                       5.z.P.w.                                                  8.B.B.8.                                                                            e #@!.F h+                                  '@)@e.!@          ! 8 8  .                              a+i x _+              & * * 2.                                          6+| K.l.                w.[.V g+                                                                                ",
"            a+i x _+                                                :.* = 5+            + * = k..                                     4.9+P.#+3.                                                q+B.B.r+                                                                              J !.>+=@                                  ~@'.f.{@          ~ > { /                               a+i x _+              7+|+|+7+                                          1+= = &                 j+[.T.k+                                                                                ",
"            a+i x _+                                              [ 1+= * &             . k.| * +                                     3.#+P.9+4.                                                l+;.d.m+                                                                              f+~.f.H K                                 f+).!.e+          { > {                                 ( i x t+              @ |+|+O.                                          & * R -                 ]@S.S.A.                                                                                ",
"            a+i x _+                                              o.N.= } o.              O.* = O.                                      w.P.z.5.                                                D ;.d.*.                                                                              e K ).!.;+e                             H.I !.)@^@          { > {                                 ' N N A+              . p+| .+                                          @ n.n.-                 w+z.P.j+                                                                                ",
"            a+i x _+                                              :.(.(.2.                @ n.R R.m                                     w.P.z.5.                                                D ;.d.*.                                                                                e F !.f.e+/@                          h+'.f.#@            { > {                                 |.9 6 3                 _.| _.                                          . .+| Q.t.              4.9+P.#+3.                                                                              ",
"            a+i x _+                                              m.= R 2.                . 1+= | 2.[                                   w.P.z.5.                                                D ;.d.*.                                                                                  K ~.f.f.e+/@                        (@>+!.e+            { > {                                 ] 9 6 ..                /././.                                            O.* Q O.              3.<.[.W w+                              u t s s ]+w.w.]+t u                             ",
"            a+i x _+                                              <+= R B+                  t.* = @.m                                   w.P.z.5.                                                D ;.d.*.                                                                                  e E ~.e.f.F E e                   /@F !.'.K             { > {                                 t+Z 6 M+                                                                  @ |+(.O.                A.T.[.#+v.s s p w+5.5.5.]@o+v.s v.y.X X W W W U [.[.U X Y                             ",
"            a+i x _+                                            [ M.= l O                   . m.= = m.                                  w.P.z.5.                                                D ;.d.*.                                                                                    e _@J e.!.).f+e             H._@%@f.f.e+              a+> ~ :@                              % : i a $                                                                 . m m o.                o+W S.T.W W S.S.V z.z.z.z.T.W W W T.T.T.W W W U S.S.U X Y                             ",
"            a+i x _+                                            k N.R M.[                     l.K.= L.[                                 w.P.z.5.                                                C -.d.=.B                                                                                       h+{@f.f.>+;+E g f f g +@I -@!.>+$@<@              h ~ ~ /                               $ ,+N [@$                                                                                         u Y V+y.W W S.T.[.P.P.P.P.X W W W X X y.v.s s s s s s t u                             ",
"            a+i x _+                                            O n.= L.                      [ 5+= n.:.                                w.P.z.5.                                                B =.d.-.C                                                                                         /@E ~.e.!.).).G H ).f.>+!.f.-@@@                / h h /                                 i.# # $                                                                                               u t s w.x.<.w.w.w.%+}@t s t u                                                   ",
"            a+i x _+                                            }+* Q }                         |@R Q <+[                               w.P.z.5.                                                  *.d.;.D                                                                                           e K I 1@!.).G !.).f.).$@e+^@e                 :@/ / :@                                                                                                                                                                                                                      ",
"            a+i x _+                                            7+* R 2@                        O K.Q n.+                               w.P.z.5.                                                  *.d.;.D                                                                                                 K E G.E E G.+@g e                                                                                                                                                                                                                                                     ",
"            a i x %                                             O.n.n.}+                        [ & * Q } .                             w.P.z.5.                                                  *.d.;.D                                                                                                                                                                                                                                                                                                                                                                       ",
"            :+> { $                                             .+| p+.                           o.R.= * u+                  3.5.3@3@d+#+}.z.5.                                                B =.d.-.C                                                                                                                                                                                                                                                                                                                                                                       ",
"            { > {                                               p+| p+                            [ m )+Q Q..                 Y z.}.[.[.[.T.P.4@w.w.w.%+&+                                      C -.d.=.B                                                                                                                                                                                                                                                                                                                                                                       ",
"          / { > 4+! |.|.|.|.|.! ~ { { { { { { { { { ; #         p+| p+                              [ k.| `.O..               Y P.T.T.T.T.T.T.[.P.P.P.U Y                                       D ;.d.*.                                                                                                                                                                                                                                                                                                                                                                        ",
"          / { 8 > 8 8 8 8 8 8 8 > > > > > > > > > > > #         6+| 6+                                + (.= (.+               &+w.T U.S.P.S.V 3+z.z.z.A.Y                                       C >.b.E.                                                                                                                                                                                                                                                                                                                                                                        ",
"          / # ; ~ 8 8 8 8 8 8 8 { { { { { { { { { { ; #         _.(._.                                . O.(.* +                     3.4.5.5.5.5.5.5.5.4.3.                                      B ,.,.F.                                                                                                                                                                                                                                                                                                                                                                        ",
"                /  .|.|.|.|.|. ./                               /.j./.                                  . + + @                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ",
"                                                                [ [ [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "};
