/* XPM */
static char * instructionsS_xpm[] = {
"280 80 316 2",
"  	c #000000",
". 	c #1F7014",
"+ 	c #2A911D",
"@ 	c #31A522",
"# 	c #1E0946",
"$ 	c #2C1062",
"% 	c #2D9B1F",
"& 	c #38B927",
"* 	c #3FCC2D",
"= 	c #3CC52A",
"- 	c #3BC22A",
"; 	c #36B326",
"> 	c #288A1B",
", 	c #104709",
"' 	c #3B187F",
") 	c #5124A8",
"! 	c #471F96",
"~ 	c #32A722",
"{ 	c #3ABE29",
"] 	c #3DC82B",
"^ 	c #41D22E",
"/ 	c #41D12E",
"( 	c #40D02D",
"_ 	c #3FCD2D",
": 	c #3BC029",
"< 	c #33AB24",
"[ 	c #441D90",
"} 	c #5727B4",
"| 	c #38B727",
"1 	c #40CF2D",
"2 	c #3ECA2C",
"3 	c #3ABD29",
"4 	c #37B626",
"5 	c #431C8D",
"6 	c #4C219F",
"7 	c #5325AC",
"8 	c #5224AA",
"9 	c #5425AE",
"0 	c #5124A9",
"a 	c #4D22A0",
"b 	c #451E92",
"c 	c #33146E",
"d 	c #19073D",
"e 	c #401B88",
"f 	c #5526B0",
"g 	c #30A121",
"h 	c #30A221",
"i 	c #3DC62B",
"j 	c #65115A",
"k 	c #701464",
"l 	c #32042C",
"m 	c #471F95",
"n 	c #4F23A5",
"o 	c #5928B7",
"p 	c #5827B6",
"q 	c #5928B8",
"r 	c #5727B5",
"s 	c #288C1B",
"t 	c #47093F",
"u 	c #9B1F8A",
"v 	c #8C1B7D",
"w 	c #07393D",
"x 	c #1B7F87",
"y 	c #17737A",
"z 	c #3F1A86",
"A 	c #5627B3",
"B 	c #492099",
"C 	c #3DC52B",
"D 	c #40D02E",
"E 	c #39BC28",
"F 	c #AD249B",
"G 	c #C42AAF",
"H 	c #BC28A8",
"I 	c #621057",
"J 	c #03272B",
"K 	c #0D4F55",
"L 	c #115E64",
"M 	c #13646B",
"N 	c #150C01",
"O 	c #7F5B18",
"P 	c #AF8025",
"Q 	c #C28E2A",
"R 	c #C08C29",
"S 	c #BD8A29",
"T 	c #B68526",
"U 	c #91691D",
"V 	c #5828B7",
"W 	c #5425AF",
"X 	c #5828B6",
"Y 	c #40CE2D",
"Z 	c #A72295",
"` 	c #C72BB2",
" .	c #CE2DB8",
"..	c #14676E",
"+.	c #26A7B2",
"@.	c #28ACB7",
"#.	c #25A1AC",
"$.	c #381778",
"%.	c #3FCB2C",
"&.	c #3CC42A",
"*.	c #3FCE2D",
"=.	c #BD28A9",
"-.	c #D12EBB",
";.	c #CA2CB4",
">.	c #731567",
",.	c #BA28A7",
"'.	c #B426A1",
").	c #105B62",
"!.	c #239BA5",
"~.	c #26A6B1",
"{.	c #26A5B0",
"].	c #25A4AE",
"^.	c #25A2AC",
"/.	c #25A3AE",
"(.	c #239CA5",
"_.	c #1F8E97",
":.	c #18777F",
"<.	c #1D8790",
"[.	c #1A7E86",
"}.	c #177178",
"|.	c #A77A23",
"1.	c #CC952C",
"2.	c #D1992E",
"3.	c #D29A2E",
"4.	c #CE972D",
"5.	c #CA942C",
"6.	c #BC8928",
"7.	c #A27621",
"8.	c #250D55",
"9.	c #4B219D",
"0.	c #4E22A3",
"a.	c #5023A7",
"b.	c #5827B5",
"c.	c #5626B2",
"d.	c #BF29AA",
"e.	c #CF2DB9",
"f.	c #C52BB0",
"g.	c #7F1871",
"h.	c #0E5258",
"i.	c #239DA7",
"j.	c #28ADB8",
"k.	c #4A209B",
"l.	c #2B951E",
"m.	c #35AF25",
"n.	c #C22AAD",
"o.	c #CB2CB6",
"p.	c #7A176D",
"q.	c #28ABB6",
"r.	c #26A8B3",
"s.	c #27A8B3",
"t.	c #2298A2",
"u.	c #C6912B",
"v.	c #C8922B",
"w.	c #CF982D",
"x.	c #D0982D",
"y.	c #C7912B",
"z.	c #B78627",
"A.	c #A17521",
"B.	c #705114",
"C.	c #5526B1",
"D.	c #4D22A2",
"E.	c #5425AD",
"F.	c #2D991F",
"G.	c #C92CB3",
"H.	c #D02DBA",
"I.	c #AF259D",
"J.	c #26A7B1",
"K.	c #25A4AF",
"L.	c #196210",
"M.	c #991F89",
"N.	c #239CA6",
"O.	c #249FAA",
"P.	c #249FA9",
"Q.	c #27A9B4",
"R.	c #C9932C",
"S.	c #A57822",
"T.	c #B98727",
"U.	c #CB952C",
"V.	c #33AA23",
"W.	c #A0218F",
"X.	c #CD2DB8",
"Y.	c #CB2CB5",
"Z.	c #BE29AA",
"`.	c #28ADB7",
" +	c #1C858D",
".+	c #32A723",
"++	c #B927A5",
"@+	c #2297A1",
"#+	c #27AAB5",
"$+	c #24A0AA",
"%+	c #21959F",
"&+	c #209099",
"*+	c #2297A0",
"=+	c #21949D",
"-+	c #C4902A",
";+	c #D0982E",
">+	c #473209",
",+	c #C7922B",
"'+	c #5727B3",
")+	c #4B209C",
"!+	c #AA2398",
"~+	c #C229AD",
"{+	c #CC2CB6",
"]+	c #CA2CB5",
"^+	c #0A454A",
"/+	c #3EC92B",
"(+	c #3EC92C",
"_+	c #247F18",
":+	c #B727A4",
"<+	c #956C1E",
"[+	c #BE8B29",
"}+	c #4C22A0",
"|+	c #5426AF",
"1+	c #AE249C",
"2+	c #D22EBB",
"3+	c #21939D",
"4+	c #27ABB6",
"5+	c #35B125",
"6+	c #39BA28",
"7+	c #C129AC",
"8+	c #C48F2A",
"9+	c #D0992E",
"0+	c #B326A0",
"a+	c #249EA8",
"b+	c #3CC32A",
"c+	c #2E9C20",
"d+	c #C52AB0",
"e+	c #D22EBC",
"f+	c #C82BB2",
"g+	c #8A641B",
"h+	c #C18D29",
"i+	c #C5902A",
"j+	c #AB7D24",
"k+	c #3BC129",
"l+	c #8A1B7B",
"m+	c #A22190",
"n+	c #B38326",
"o+	c #624610",
"p+	c #4E22A2",
"q+	c #25A1AB",
"r+	c #25A3AD",
"s+	c #CC2DB7",
"t+	c #BA8828",
"u+	c #4F23A6",
"v+	c #2E1164",
"w+	c #CE2DB9",
"x+	c #27A9B3",
"y+	c #1F8C95",
"z+	c #40D12E",
"A+	c #3DC72B",
"B+	c #A52293",
"C+	c #B28225",
"D+	c #5325AD",
"E+	c #A72395",
"F+	c #27AAB4",
"G+	c #B626A2",
"H+	c #911D82",
"I+	c #CC962D",
"J+	c #996F1F",
"K+	c #BD29A9",
"L+	c #CD2DB7",
"M+	c #9C7220",
"N+	c #CD962D",
"O+	c #36B225",
"P+	c #2FA021",
"Q+	c #BD8A28",
"R+	c #735315",
"S+	c #1E8C95",
"T+	c #C32AAE",
"U+	c #931D83",
"V+	c #26A6B0",
"W+	c #401B87",
"X+	c #B2259F",
"Y+	c #1E8992",
"Z+	c #C62BB1",
"`+	c #5023A6",
" @	c #26A8B2",
".@	c #3D1982",
"+@	c #D02EBA",
"@@	c #491F99",
"#@	c #4D22A1",
"$@	c #5525AF",
"%@	c #431D8D",
"&@	c #811873",
"*@	c #39177A",
"=@	c #5225AB",
"-@	c #3ABD28",
";@	c #207315",
">@	c #CC2CB7",
",@	c #28ACB6",
"'@	c #26A5AF",
")@	c #C029AC",
"!@	c #B226A0",
"~@	c #AA7C23",
"{@	c #A77A22",
"]@	c #3ABF29",
"^@	c #C82BB3",
"/@	c #C92CB4",
"(@	c #37B526",
"_@	c #951E85",
":@	c #B1259E",
"<@	c #BA28A6",
"[@	c #C92BB3",
"}@	c #36B426",
"|@	c #D2992E",
"1@	c #8C651B",
"2@	c #AB2499",
"3@	c #CC962C",
"4@	c #B927A6",
"5@	c #3FCC2C",
"6@	c #C029AB",
"7@	c #A12190",
"8@	c #9B701F",
"9@	c #C5902B",
"0@	c #C38E2A",
"a@	c #471E95",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                . + @ + .                                                                                                                                                                                                                                                                                                                                                                                                                                       ",
"                                        # $ $ #                                             # $ $ #                           % & * * * = - ; > ,                                                                                                                                                                                                                                                                                                                                                                                                                               ",
"                                        ' ) ) '                                             $ ! ! $                     , ~ { ] ^ * * * ^ / ( _ : <                                                                                                                                                                                                                                                                                                                                                                                                                             ",
"                                        [ } } [                                             ' ) ) '                   , | 1 ^ ^ 2 3 @ 4 = 1 / / ^ = + .                                                                                                                                                                                                                                   5 6 7 8 9 9 9 9 9 7 0 a b c d                                                                                                                                                         ",
"                                        ! } } !                                             e f f e                   g 1 ^ ^ / ] .     . h | 2 1 / 1 i .           j k k l                                                                                                                                                                                                         $ m n f o p q q q q q q q o o r 9 n 5 $                 s s s                                               t u u v                                                   w x x y               ",
"                                        z A A B                                             [ A A [                   2 ^ ^ / C g .           . < 1 ^ D E .         F G H I                                           t u u v                               J K L M L L K w                               N O P Q R S S T U                                                     $ 5 8 r V o p p W 9 9 9 9 9 W r o r X o p W ' $             & Y &                                           t u Z `  .F                                                   ..+.@.#.              ",
"                                        $.f X a                                             [ A A [                   %.^ ^ &.,                 . 3 *.^ Y h         =.-.;.>.                                          t ,. .'.t                             ).!.~.+.{.{.].^./.(._.:.<.[.}.L L K w         |.1.2.3.3.4.2.2.5.6.7.                                                b } V q p W 6 ' $           8.b 9.0.a.b.q V c.6 $           &.^ i ,                                         I d.e. .-.f.g.                  J ).).h.                      i.@.j.~.              ",
"                                        8.9 X 0 d                                           [ } } k.                l.Y / D +                       m.Y / E         n.-.o.p.                                          t n.-.;.g.                            ).#.@.@.q.q.q.@.j.j.r.s.s.s.{.{.{.{.t.x       u.3.3.2.v.4.w.x.2.2.y.z.A.B.                                        # 9 q q C.B c d                       8.D.E.X o b.6 $         &./ Y F.                                        >.G.H. .-.e.I.                  K !.#._.                    w J.j.j.K.              ",
"                                        d 9.X 9 5                                           ' A p 6                 m./ / E .                       L.2 ^ %..       =.H.G.>.                                            n.-.e.M.                            h._.N.O.N.N.P.Q.j.j.j.s.s.s.q.q.q.q.j.x       R.3.3.v.O U S.T.U.w.2.x.4.T B.                                      $ r q q n                                 $ 6 b.o } m         & / / V.                                        W.X.-.Y.e.-.Z.                  K J.`.~...                  P.j.j.@. +              ",
"                                          5 9 q B                                           $ 9 A )                 { ( 1 .+                          : ^ 1 <       =.H.G.>.                                            ++-.e.I.                                        w @+#+q.$+%+<.&+*+N.N.P.=+x       -+;+;+S.      >+O P ,+2.2.w.T >+                                    $ '+q o )+                                  $ 6 V o f $       V.1 1 &                                         !+-.-.~+{+-.]+g.                ^+/.j.q.[.                  Q.j.j./.).              ",
"                                          ' A A 6                                             ) q )               l./+/ (+_+                          < %.^ : ,     =.H.G.>.                                            W.o.-.:+                                          *+q.{.}.                        R 3.u.B.          >+<+[+x.3.U.A.                                    # }+b.r 9.                                    $ |+q p [ $     _+(+( E                                         ++e.e.1+n.2+e.M.                  3+4+4+3+                [.j.j.j.<.                ",
"                                          [ A A [                                             9 q 9               5+/ / 6+,                             E ( (+_+  t 7+H.` I                                             I G.H.7+                                          N.q.{.L                       >+u.3.8+                B.6.9+3.v.B.                                    $.f X a                                       6 } V c.m     , &.^ &.,                                       H H.G.g.0+e.e.0+                  ..].@.$+..            w a+j.j.#+                  ",
"                                          [ A A [                                             9 q 9               b+/ _ c+                              ; Y Y .+  I ` H.7+t                                             t d+e+f+k                                         N.q.{.L                       g+U.2.h+                  B.i+3.w.j+>+                                  8.9 X 0 d                                     $ 6 p X 6       k+( (+L.                                    t G e+G t g.G.H.H                   w !.@.q.t.            }.q.j.j./.                  ",
"                                          [ A A [                                             9 q 9             l.2 ^ &.,                               ; ( / |   l+G.H.:+                                                n.-.e.m+                                        N.q.{.L                       n+x.2.z.                    j+5.2.8+o+                                  d 0 X 9 8.                                      z } } p+      | ( (+>                                     I G.H.7+  t G e+f.I                    +4+`.q+w         w r+j.j.4+:.                  ",
"                                          [ A A [                                             9 q 9             m./ / E                                 ~ 1 / k+, M.s+s+I.                                                I.H.-.H                                         N.q.{.L                       T.2.w.P                       t+;+5.g+                                    u+X f v+                                      c 9 X n d     m.Y Y V.                                    l+G.H.:+    H -.w+I.                  ).^.q.x+y+        3+@.j.j.^.                    ",
"                                          [ A A [                                             ) q 9 $           { ( 1 .+                                _+- z+A+_+B+s+s+B+                                                g.d+e+G k                                       N.q.{.L                       C+4.4.S.                      [+x.w.|.                                    u+X f v+                                      d D+V C.8.    @ 1 / 3                                     ++e.e.I.    E+e.2+Z.                    [.F+@.!.      ).Q.j.j.F+..                    ",
"                                          [ A A [                                             6 A A '         , { D ] _+                                  m.* * F.B+s+s+B+                                                  G+s+s+H+                                      N.q.{.L                       P I+I+J+                      n+2.2.z.                                    u+X f v+                                        0 o f 8.    @ 1 / 3                                     K+e+e.B+    g.L+-.f.                    ..~.`.s.y+  ).N.j.j.j.%+                      ",
"                                          [ A A [                                             [ A A [         L.A+( k+,                                   @ * * @ ++e.e.!+                                                  0+e.e.I.                                      N.q.{.L                       z.x.R.g+                      M+N+2.h+                                    u+X f v+                                      m c.p ) d     @ Y Y O+                                    K+e.e.B+    t G e+G t                   w &+4+j.!.  y+@.j.j.s.).                      ",
"                                          ' f A 6 $                                           [ A A [         P+%.z+|                                     @ * * @ d.2+H.W.                                                  0+-.-.:+                                      N.q.{.L                       Q+x.R.R+                      >+u.3.8+                                    u+X f v+                                    ' 9 q } z       @ * * @                                     B+s+s+B+      n.-.X.M.                    ..s.@.{.}.K.j.j.@.S+                        ",
"                                          $ ) A f $                                           [ A A [         & / 1 m.                                    @ * * @ T+-.X.U+                                                  Z w+-.7+                                      N.q.{.L                       h+x.R.o+                        u.3.u.                                    u+X f v+                              d c B f o q f c       @ * * @                                     I.s+s+M.      ++-.-.!+                    w !.@.#+V+q.j.j.F+..                        ",
"                                            ) q 9 $                                           [ A A [         - / 1 F.                                    @ * * @ =.H.G.>.                                                  I f+e+G                                       N.q.{.L                       8+3.u.>+                        u.3.u.                                    u+X f v+                          $ ' 6 W p q V 9 W+d       @ * * @                                     H H.G.g.      X+e.e.X+                      Y+4+j.@.j.j.@.*+w                         ",
"                                            9 q 9                                             [ A A [         - z+%._+                                    @ * * @ =.H.G.>.                  v u u t                         t Z+e+G                                       N.q.{.L                       u.3.u.                          u.3.u.                                    a X f $.                  $ 5 a 0 D+p p o V b.`+'           @ * * @                                     G e+Z+t       M.s+s+I.                      .. @j.j.j.j.K.y                           ",
"                                            9 q 9                                             [ A A [         &.^ i ,                                     @ * * @ 7+H.G.I                   =.H.G.>.                        t ` H.G t                                     N.q.{.L                     B.u.3.R                           u.3.u.                                    B A A z         d 8.$.z 6 ) } o o q p o f n m $             3 1 1 @                                   t Z+e+G         g.` H.H t                     w =+@.j.@.j.#.                            ",
"                                            9 q 9               $ ' [ [ [ [ [ [ [ [ [ [ B a u+9 V V f .@      i ^ i                                       @ * * @ G e+Z+t                   o.e++@v                         t 7+H.` I                                     N.q.{.L                     U I+I+T                           u.3.u.                                  d @@} } #@z [ [ 6 ) c.} p } q } p p E.7 6 5                   3 ^ 1 @                                   g.G.H.H         t n.-.L+M.                      y t.J.j.@.!.                            ",
"                                            $@q p 7 9 9 9 9 9 9 A p p A A A A A A A A A A X X V q q o %@      i ^ i                                       @ * * @ Z+e+Z+                    e.e+-.v                           =.H.G.>.                                    N.q.{.L                     S.I+I+S.                          u.3.u.                                  W+C.q q r A A r p q V q V } ) D.9.b c                         3 1 1 @                                   !+ . .I.          ++-.-.!+                          $+4+4+ +                            ",
"                                            $@q q q q q q q q q q q p A A A A A A A A A A f f c.o q b.%@      i ^ i                                       m.* * F.Z+e+Z+                    e.e+-.&@                          =.H.G.>.                                    N.q.{.L                     S.I+I+S.                          u.3.u.                                  W+V q q o A A r q '+9 D+8 [ $                                 @ * * @                                   K+-.e.B+          X+e.e.X+                         +K.j.a+).                            ",
"                                            $@q p 7 9 9 9 9 9 9 f 7 `+[ [ [ [ [ [ [ [ [ z $.v+.@c.V 0 d       i ^ i                                       | ( (+> Z+e+Z+                    H.e+-.>.                          =.H.G.>.                                    N.q.{.L                     S.I+I+S.                          u.3.u.                                  *@=@V V W B [ p+6 m d                                         m.* * F.                                  K+-.e.!+      k H+=.-.-.]+B+B+H+k                 %+j.4+%+                              ",
"                                            9 q 9                                             v+f X u+        i ^ i                                       -@( (+;@Z+e+Z+                    H.e+-.U+                          =.H.G.>.                                    N.q.{.L                     S.I+I+S.                          u.3.u.                                    B A A z                                                     | ( (+>                                   +++@-.>@Z+Z+Z+Z+s+e.e+e+-.s+s+Z+u                 $+4+4+[.                              ",
"                                            9 q 9                                             v+f X u+        i ^ i                                       -@( (+;@Z+e+Z+                  k e.e+2+0+                          =.H.G.>.                                    N.q.{.L                     S.I+I+S.                          u.3.u.                                    a X f $.                                                    k+( (+L.                                  H -.2+e+e+e+e+e+s+ .e+e+-.s+s+Z+u               w i.,@'@..                              ",
"                                            ) q 9 $                                           v+f X u+        i ^ i                                     , k+( A+L.Z+e+Z+                  H+-.e+e+++                          =.H.G.>.                                    N.q.{.L                     S.I+I+S.                        >+u.3.8+                                    u+X f v+                                                    &.^ i ,                                 t G e+ .f.Z+Z+Z+)@G+!@e.-.]+B+B+H+k               [.~.@.!.w                               ",
"                                            6 A A '                                           v+f X u+        i ^ i                                     _+A+( E , Z+e+Z+                  B+-.e+-.X+                          =.H.G.>.                                    N.q.{.L                     S.I+I+S.                        o+R.x.h+                                    u+X f v+                                                    i ^ i                                   I G.H.7+            >.G.H.=.                      t.@.4+&+                                ",
"                                            [ A A [                                           8.9 X 0 d       i ^ i                                     F.Y Y &   Z+e+Z+                  B+-.e+-.B+                          =.H.G.>.                                    N.q.{.L                     S.I+I+S.                        g+R.x.z.                                  d 0 X 9 8.                                                  , i ^ &.                                  l+G.H.:+            I G.H.7+                      $+@.4+[.                                ",
"                                            [ A A [                                           d 0 X 9 8.      i ^ i                                     m.1 / &   Z+e+Z+                  I.H.e+H.I.                          =.H.G.>.                                    N.q.{.L                     U R.I+T B.                      J+I+I+P                                   8.9 X 0 d                                                   L.(+( k+                                  ++e.e.I.            t Z+e+G                       $+@.+...                                ",
"                                            [ A A [                                             u+X f v+      : ^ ] _+                                  E / ( m.  Z+e+Z+                t H -.-.-.:+                          7+H.G.I                                     N.q.{.L                     O R I+v.B.                      P 4.4.~@                                  v+f X u+                                                    ;@(+( -@                                  K+e+e.B+              Z+e+Z+                    w #.j.#.w                                 ",
"                                            [ A A [                                             u+X f v+      4 1 ( 4                                   &.^ (+_+  )@e+Z+k               g.` -.H.+@=.                        k G e+)@t                                     N.q.{.L                     o+8+x.h+B.                      z.2.x.n+                                  v+f X u+                                                    P+%.z+|                                   n.e.e.M.              Z+e+Z+                    [.+.@.!.                                  ",
"                                            [ A A [                                             a X f $.      @ 1 ^ 3                                   i ^ i     G+ . .B+              0+e.H.e.H.7+t                       H+ . .K+                                      *+q.{.}.                    o+y.x.h+>+                    >+h+2.w.{@                                  v+f X u+                                                    & / 1 m.                                  H H.G.g.              )@e+Z+k                   t.@.4+&+                                  ",
"                                            [ A A [                                             B A A z       F.1 1 ]@                                . i ^ :     B+e.-.K+            k n.2+e.;.H.` I                       B+e.-.K+                                      &+s.s.[.                    >+h+2.5.g+                    O y.2.Q O                                   v+f X u+                                                    3 / 1 @                                   G e+Z+t               G+s+s+H+                  $+@.4+[.                                  ",
"                                            [ A A [                                             [ } } k.      > (+( |                                 < * * <     B+e.-.K+            B+H.-.^@7+-.o.W.                      G+e.-.G+                                      <.s.s.<.                      z.2.x.n+                    ~@w.w.T.                                    $.f X a                                                     O+Y Y @                                 g./@e+G                 B+s+s+B+                  $+@.+...                                  ",
"                                            [ A A [                                             [ p V `+      L.A+( k+,                             . : ^ : .     M. . .++            ++-.-.!+I.e.-.++                    t d+e+]+H+                                      <.s.s.<.                      P w.2.T.                    S 2.2.S.                                    z A A B                                                     @ Y Y (@,                               I.H.-.H                 B+L+L+!+                 +~.j.a+w                                   ",
"                                            [ A A [                                             z p V 8       , E / _ m.                            m.1 1 &       l+G.H.:+          v G.-.L+M.M.e.-.n.                    _@X.2+f.                                        :././.:.                      U N+x.v.A.                B.5.3.N+U                                     [ A A [                                                     @ 1 / Y i i i i i i i i i i i i i & %   Z.-.e.E+                B+e.H.K+                %+j.4+%+                                    ",
"                                            [ A A [                                             $.c.V a.        m.1 ^ &                           , i ^ ( F.      I ` H.7+t         :@-.-.Z.t g.o.-.n.                  t <@-.H.:+                                        ).x x ).                      B.6.2.3.P               >+j+w.2.R                                       [ A A [                                                     + * / / ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ %   n.-.o.g.                B+e.2+K+                $+4+4+[.                                    ",
"                                            [ } } k.                                            v+f X u+        + 1 1 =                           ~ Y ^ %._+      t H -.;.M.      v ;.2+e.Z   t )@e+f+H+                _@L+-.[@g.                                                                        7.x.2.5.O           B.T.N+2.5.j+                                      [ A A [                                                     . < E - &.i i i i i i i i i i i i & % m+;.e+)@t                 M.e.e.d.                i.,@~...                                    ",
"                                            [ p V `+                                            v+f X u+        . &.^ = _+                      s C ^ 1 }@          I.e.-.++    k H -.-.Z.I     G+e.-.G+              t :+-.-.:+                                                                          B.Q |@x.~@O >+>+  1@T w.3.4.|.>+                                      k.p p k.                                                                                          2@-.s+2@                  g.d. .m+                =+j.t.w                                     ",
"                                            [ p V `+                                            v+f X u+          | / ( 6+,                 , < (+^ / : .           B+e.-.K+  k G+H.-.f+_@      H+e.-.^@k             _@o.-./@_@                                                                            P I+2.w.3@u.h+Q+v.2.2.x.R B.                                        0.o o 0.                                                                                          2@d.4@k                   t u u v                 x x x                                       ",
"                                            [ } } k.                                            v+f X u+          l._ ^ Y m..             _+; 5@^ ^ &.s             H+L+ .6@>.G+e.-. .2@        k f+e+e.7@          v Z.-.-.:+                                                                              B.8@9@2.2.x.x.x.2.3.4.P B.                                          k.V V k.                                                                                          t t t                                                                                         ",
"                                            [ A A [                                             8.f X 0           , E / ^ 1 E .+_+, , > ; i ( / D C g               k H -. .^@X.e+H.G+k           :+-.-.[@2@k     t H -.-.;.7@                                                                                  |.R v.0@y.R.R.R j+B.                                            ' p+p+'                                                                                                                                                                                         ",
"                                            [ A A [                                             d 9 q 7             s &.^ D / 1 ] k+k+2 ( / / Y 4 .                   m+e.e+-.e+H.H k             _@G -.e+e.n.G+X+G H.e+e.Z t                                                                                         >+o+R+o+>+                                                                                                                                                                                                                                                ",
"                                            a@} } [                                               7 q 9 d             % < ] / ( D ( ( z+/ 1 - h .                     k G e+2+ .H k               t u G -.+@e+e.e.-.e+e.H k                                                                                                                                                                                                                                                                                                                                                     ",
"                                            `+p p [                                               9.} a.d                 l.m.{ { A+A+k+| h .                           u '.H m+k                     v 2@d+ .-.e.e.o.G+k                                                                                                                                                                                                                                                                                                                                                       ",
"                                            6 o A '                                               *@W+W+d                       , L.L.,                                                                   k 2@G+X+M.g.t                                                                                                                                                                                                                                                                                                                                                         ",
"                                            5 9.9.$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "};
