/* XPM */
static char * newgame_xpm[] = {
"280 80 75 1",
" 	c #000000",
".	c #010101",
"+	c #595959",
"@	c #BDBDBD",
"#	c #ABABAB",
"$	c #030303",
"%	c #787878",
"&	c #E8E8E8",
"*	c #FAFAFA",
"=	c #D3D3D3",
"-	c #8D8D8D",
";	c #F4F4F4",
">	c #FDFDFD",
",	c #E6E6E6",
"'	c #9B9B9B",
")	c #CCCCCC",
"!	c #DFDFDF",
"~	c #ECECEC",
"{	c #CFCFCF",
"]	c #8A8A8A",
"^	c #C3C3C3",
"/	c #E1E1E1",
"(	c #C5C5C5",
"_	c #7D7D7D",
":	c #C0C0C0",
"<	c #F8F8F8",
"[	c #FCFCFC",
"}	c #F1F1F1",
"|	c #F9F9F9",
"1	c #D5D5D5",
"2	c #D0D0D0",
"3	c #DDDDDD",
"4	c #EFEFEF",
"5	c #E9E9E9",
"6	c #F7F7F7",
"7	c #FEFEFE",
"8	c #E5E5E5",
"9	c #B1B1B1",
"0	c #F6F6F6",
"a	c #C9C9C9",
"b	c #FFFFFF",
"c	c #FBFBFB",
"d	c #EEEEEE",
"e	c #EAEAEA",
"f	c #DBDBDB",
"g	c #F5F5F5",
"h	c #F2F2F2",
"i	c #E7E7E7",
"j	c #A8A8A8",
"k	c #BBBBBB",
"l	c #D6D6D6",
"m	c #9E9E9E",
"n	c #C4C4C4",
"o	c #DADADA",
"p	c #B6B6B6",
"q	c #F0F0F0",
"r	c #999999",
"s	c #535353",
"t	c #3F3F3F",
"u	c #CBCBCB",
"v	c #9F9F9F",
"w	c #E2E2E2",
"x	c #DEDEDE",
"y	c #D1D1D1",
"z	c #EBEBEB",
"A	c #BFBFBF",
"B	c #C6C6C6",
"C	c #EDEDED",
"D	c #B5B5B5",
"E	c #D8D8D8",
"F	c #CACACA",
"G	c #B3B3B3",
"H	c #D2D2D2",
"I	c #E4E4E4",
"J	c #D9D9D9",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                .   +@@#                                                                                                                                                                                                                                ",
"                                                $   %&*=                                                                                                                                                                                                                                ",
"                                                .   -;>,              +')!&~,{'']]                                                                                           +%-^/~&,,!(]                                                                                               ",
"                                   _:=:_        .   -;>,            ](~<[>>>>*;}|~1%                                                                                     2345};;6>>>>>7*8]                                                         +%---%+                              ",
"                                   90><a        .   -;>,           ]1*7b>66[[*>bc7*~2]                                                          ](8d}de,=#            _#f;b[bb>>>[[6;g[bc2           (3,{aaaa9]                                  ](8h;;;d5~,2+                          ",
"                                   a[b74        $   -;>,           2|77<i^jkal88h*77<(                                                          @<7bbb>>*@            ]fdb[[}de,!lkj-mi>78         +@d7[|<<c[[in+  +%jk9] ]28&!(]               +1|7>>>>c<>7<on                         ",
"                                   )cbbg        $   -;>,           5>>/p        ](q>7!   r##s                                                  (d>b<}};;&@            ](8339]         'g>~+        %&7>[|<<c77bg/2!8h;<g298c7>7[g2]             267>q,,,!dc>7b}]                        ",
"                                   a<7b*2       .   -;>,          +4bh]           ^|7&   =gi%                  +@@#                           +~7>/n +%-%+            t++t            +876)        -;>}aaaa/,6b7*>*>>>*[*}cb>6*bb|u+           phb[/'    ]93[b[)                        ",
"                                   a<[7b5       .   -;>,          1*78           +/>78   ,>;-                  %&*=                           ncb6]                                    )[7i        -;>,      @hb7b[he!/c777|/jo;770u+          177q]       9h>78                        ",
"                                   a<*[b*@          -;>,.         ib[)          (icbc2   &>0v       #@@+       j;>!                           !77w                                     j*7q        -;>,       2>bb4'+ ]4bbbx+  #877g@         +~[c(      +2~[7>f                        ",
"                                   a<<0bb2          -;>,          q7*j        '1;7bc8]   ,7cy       ,>;-       k<<l                          +z7<A                                     B|75        -;>,       ]gbb;    37b>B    #db75]        'q>i]     pw|b7c8#                        ",
"                                  .a<<Cc>hp         -;>,          ,>;-     +)i0[7>61]    !77o       6b>D       a<<a                          n67h%                                    +x77!        %;>e        5bb<    9bb7j     @hbc2        k<<l    n1;7b[g2]                         ",
"                                  .a<<E!77!         -;>,          ,>;-  +k/4<777*/'+     lcco       |bb8       a<<a                          1778+                                   ]1|7c8@#      +}bd        abb[+   ][b7F      2c7gn       a<<a  (8|b>76o'+                          ",
"                                  .a<<ap67;9        -;>,          ,>;Gn1/h>>7[<i(]       a<<a       6bb5       a<<a                          wcc)                                 +%ui[77&6>,       5b}]       9>b>-    *bbq      ]87b8       yc>0qd<7b7c!p+                            ",
"                                   a<<a+1[>5    .   -;>,         (<b[d*[*>[c~)'+         k<<l       ;bbq       E[[E                         +8>h'                              +pEeg*b>7eH>b6      +4[c9        <b>m    ~bb0       #6bh+      E>bb7bb[68(]                              ",
"                                   a<<a ]gbg]   .   -;>,         fbb7777|8l9]            ';>8       hbb02      E>>E                         'h>8+                            ]24*7>>7c42#D7b*      %6b>a        ,>;-    l7bg        8>6k      a>77|}~1'                                 ",
"                                   a<<a  36c39  .   -;>,         f7bb|h8(]               +4b69     ]}b7b3      ,[[a                         k<<l                           +n~[bb[gqef]  D7b*      ->b7a        #@@+    j;>!        )[>i      v4bc5'                                    ",
"                                   a<<a  ]5[>2      -;>,         ]qb78%+                  ,>>a     9*[7>6'     5b}]                         a<<a        ]aEEE,39           n;b7[;wj+     #7bc%     ->b7a                +@@#        j*7q       2*b[ip+                                  ",
"                                   a<<a   2b>hp     -6>C          )*7e+                   {[[I+    a[7*7[I'+  #}b8                          a<<a       @/[>[*>>hef@+      @877h2]        G7b7u     %[b7l                            %6>q       ]8c77*}l]                                ",
"                                   a<<a   @~771     j*7q          +5b|1+                  'h70u+   l[>h}b>;@ ]8>hn                          a<<a       @b[>[*[[b>>&'      /b6f#          k7bbo     +hbb&                            +5bd]       ]24[bb[}8e!laakj----%+                  ",
"                                   a<<a$   (c76u    k[>~           2cb*wp+                +!7703kjGq70k@}b7}5,c>5+                          a<<a       @2,EEaa35*[<'     +}bd            l7b7w      ibb6                             3ccl         '!<>><b77*<<<;;;;;&@                  ",
"                                   a<<a.   ]!7b~]  +,cca .         ]e7b7*53aaa,,3]         ph77[*;6>>5+ 28hbb*[<2                           a<<a               +~b}]     %;>e           +8777~'     Jbb*                             a[7,           '{/54[[*<<<>>>>>*@                  ",
"                                   a<<a .   #67>1] '67h]            #f6b7b[[|<[b<@         +@8*>*>>7<2    @/}<g2]                           a<<a               #}b8      -;>,           'g>c7[1     F7b<                             a[[,               'uo{aal!,,,,=#                  ",
"                                   a<<a     .=>>c1'/>78  .            n!qg7[|<[[<@           ]23/!,!(]      ]99]                            k<<l              @e7hn      -;>,          (5>>;[70@    jg>w                             9||/                                               ",
"                                   a<<a      #87>ci|b09                  (3,{aaa9]                                                          ';>~]            #}b7/+      %;>q]       (8<b7|35bb6l(] +@@#                             ]/b2                                               ",
"                                   a<<a       #87>>7>8                                                                                      +5b>ip+        ]nC7bg@       +/b>6e!laa/~<77[*1]@gb>>6@                                   @@@                                               ",
"                                   a<<a        #8>[>59                                                                                       2<77*43a9]   ]3*>7hu+        @}bb77*<<c77[6/9]  28*76@                                                                                     ",
"                                   a<<a         #28)#  .                                                                                     ]24[7b[[<}}}}g>77d@           256[[*<<c[6o'+     +n1)]                                                                                     ",
"                                   9}}9                                                                                                        '!q|b[<bbbbbbcip+             'uo{aaak'+                                                                                                 ",
"                                   ]@@]                                                                                                           23,35}}}}52]                                                                                                                          ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                        "};
