/* XPM */
static char * seven_xpm[] = {
"50 50 60 1",
" 	c #000000",
".	c #595959",
"+	c #787878",
"@	c #A8A8A8",
"#	c #CFCFCF",
"$	c #E6E6E6",
"%	c #D8D8D8",
"&	c #B1B1B1",
"*	c #8A8A8A",
"=	c #7D7D7D",
"-	c #BBBBBB",
";	c #AEAEAE",
">	c #8D8D8D",
",	c #D6D6D6",
"'	c #C9C9C9",
")	c #DDDDDD",
"!	c #EEEEEE",
"~	c #F1F1F1",
"{	c #F4F4F4",
"]	c #FAFAFA",
"^	c #FDFDFD",
"/	c #FEFEFE",
"(	c #FBFBFB",
"_	c #E1E1E1",
":	c #ABABAB",
"<	c #F9F9F9",
"[	c #F5F5F5",
"}	c #F8F8F8",
"|	c #FFFFFF",
"1	c #FCFCFC",
"2	c #F7F7F7",
"3	c #EAEAEA",
"4	c #DFDFDF",
"5	c #EDEDED",
"6	c #D0D0D0",
"7	c #CCCCCC",
"8	c #DBDBDB",
"9	c #D5D5D5",
"0	c #E9E9E9",
"a	c #ECECEC",
"b	c #C5C5C5",
"c	c #F2F2F2",
"d	c #9B9B9B",
"e	c #EFEFEF",
"f	c #BDBDBD",
"g	c #C4C4C4",
"h	c #E8E8E8",
"i	c #646464",
"j	c #ACACAC",
"k	c #9E9E9E",
"l	c #D1D1D1",
"m	c #DADADA",
"n	c #E7E7E7",
"o	c #E5E5E5",
"p	c #D3D3D3",
"q	c #F0F0F0",
"r	c #F6F6F6",
"s	c #F3F3F3",
"t	c #B6B6B6",
"u	c #E2E2E2",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                             ...    .+@#$$%&*     ",
"          =&-;>>>>@-,,,'''''')!~~~~~~{{]^//(_     ",
"          :!<[{{{{{}}^}}}}}}}}^||||||^^]1/||_     ",
"          :!<^^^^^^}}{}}}}}}}2!!~~~~!34,5^|<6     ",
"          =&,_$$$$4,---''''''&*        &$/}7      ",
"                                      *~/<8*      ",
"                                     +91/0        ",
"                                    *9[/a'        ",
"                                    6</0:         ",
"                                   :0^}b          ",
"                                  *81c9*          ",
"                                 &0(26.           ",
"                                de//)*            ",
"                                91|c&             ",
"                              .fa|~b              ",
"                              gh^8f               ",
"                            *)~|_:                ",
"                  i*&j@>klmmn1|<0)o$$p:           ",
"                  *6e]]2[(/^^||^<]^1^]f           ",
"                  *6e^/^^///|^(]<}~c{hf           ",
"                  i*'hq55r<|sn'''&d+>+.           ",
"                       ._}|_f                     ",
"                       g{/!f                      ",
"                      fo|0b                       ",
"                    .to|of                        ",
"                    6c/!g                         ",
"                   d[|16.                         ",
"                  .9^|q*                          ",
"                  gq/!b                           ",
"                 gc|!:                            ",
"                .u|/4                             ",
"                6</2t                             ",
"               *0/]6.                             ",
"               *s2o*                              ",
"               *ff*                               ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "};
